<!DOCTYPE html>
<html>
    <head>
        <title>Subhelper</title>
        <meta http-equiv="content-type" Content="text/html;charset=windows-1251"> 
       <!-- scripts -->
       <script src="/js/jquery-1.9.1.js"></script>
       <script src="/js/sammy.js"></script>
       <script src="/js/sammy.template.js"></script>
       <script src="/js/jquery.tipsy.js"></script>
       <script src="/js/nychos.storage.js"></script>
       <script src="/js/nychos.progressbar.js"></script>
       <script src="/js/subtitle.js"></script>
       <script src="/js/Phrase.js"></script>
       <script src="/js/Word.js"></script>
       <script src="/js/Dictionary.js"></script>
       <script src="/js/jquery.center.js"></script>
       <script src="/js/Translation.js"></script>
       <script src="/js/main.js"></script>
       
      
       <!-- styles -->
       <link href="/css/ui-lightness/jquery-ui-1.10.3.custom.css" rel="stylesheet" type="text/css" />
       <link href="/css/main.css" rel="stylesheet" type="text/css" />
       <link href="/css/tipsy.css" rel="stylesheet" type="text/css" />
       <link href="/css/select.css" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div id="wrapper">
            <div id="header">
                <div class="panel" id="firstPanel">
                    <div id="logo" title="toolkit for learning english">Subhelper</div>
                    <div id="uploadSubtitle">
                        <form name="upload_big" id="upload_big" class="uploaderForm" method="post" enctype="multipart/form-data" action="index/upload" target="upload_target">
                            <div class="fileWrapper">
                                    <a class="fileButton">Upload subtitle</a>
                                    <input name="subtitle" id="file" class="fileInput" size="27" type="file" />	
                            </div>        
                            <input type="submit" name="action" value="Upload Image now" class="inputSubmit" />
                        </form>
                        <div id="notice" class="notice">Wait...</div>
                         <!-- hidden iframe begin -->
                            <iframe id="upload_target" name="upload_target" src=""></iframe>
                        <!-- hidden iframe end -->
                    </div>
                </div>
                    <div id="phrasesProgressBar" class="panel"></div>
               
                    <div id="aside" class="panel">
                        <select id="sortByStatus" class="custom-select">
                            <option value="all">All</option>
                            <option value="process">Process</option>
                            <option value="waiting">Waiting</option>
                            <option value="done">Done</option>
                        </select>
                        <div class="sortSwitcher">	
                                <input type="checkbox" value="None" id="sortSwitcher" name="check" />
                                <label for="sortSwitcher"></label>
                        </div>
                    </div>
            </div>
            <div id="content">
            </div>
            <div id="infoBar" class="panel">
                <div id="lightning">
                    <img src="/img/lightning.png" />
                    <span id="lightningCounter"></span>
                </div>
            </div>
        </div>
        <script src="/js/uploadingSubtitle.js"></script>
    </body>
</html>
